### ISSUE TITLE
Permission names are too long

### ISSUE THREAD

**Issue by dgabrielson** [numbas/editor#231]
In the editor models, the permission names are too long.

The string 'Can pick exams to be featured on the front page.' has len(...) = 52; but the django auth Permissions model declares this field as max_length=50.  Mysql will silently truncate this, but PostgreSQL will throw an error.

See (e.g.): http://www.davidpashley.com/2009/02/15/silently-truncated/

**Comment by christianp** [comment]
Thanks for spotting this! I hadn't tried setting up the editor with Postgres yet.

I've spent a bit of time working through what else needs to happen when you install with Postgres. It turns out not much, but for convenience I've created a branch of the editor-vagrant scripts which uses postgres instead of MySQL; it's at https://github.com/numbas/editor-vagrant/tree/postgres

Let me know if you spot anything else!

**Comment by dgabrielson** [comment]
Hi Christian,

Thanks for this!  FYI I’ve created a github fork of both the editor and Numbas runtime for my deployment (Department of Statistics, University of Manitoba http://www.stats.umanitoba.ca <http://www.stats.umanitoba.ca/>).

I have quite a bit of Django experience (using and developing applications for 6 years now), so my hope is that I will start contributing any necessary changes back via pull requests rather than bug reports.

Cheers and thanks!

—Dave.
