### ISSUE TITLE
Exams and questions should be hidden by default

### ISSUE THREAD

**Issue by christianp** [numbas/editor#261]
You have to wade through a lot of rubbish in the editor!
When people are just messing about, they won't bother to set their content to hidden.
Stuff should be hidden by default, and there should be a big "publish" button to set content as publicly visible.
We need to go through the existing stuff and decide what should remain public, before hiding everything else and changing the default.

**Comment by BillFoster** [comment]
Something like this is now necessary both for quality of questions and for ease of searching the database. However, the users/authors should be contacted in order to get their views, especially on making judgements on their questions in terms of usability, either via the users group or contacting the active authors individually. One worry is that authors will be disinclined to publish (or just forget to).

**Comment by christianp** [comment]
Maybe as a first phase, copies should be set to hidden on creation. We'd need to have a clear "THIS IS HIDDEN TO EVERYONE ELSE" message on the question edit screen though.
