### ISSUE TITLE
Catch errors caused by missing resources

### ISSUE THREAD

**Issue by christianp** [numbas/editor#279]
When you try to run a question with a broken resource, you just get a 500 server error. Should get a more helpful error message.

**Comment by chrismgraham** [comment]
The issue seems to be caused by the 'image' field in the table 'editor_image' being empty, but the image still being linked to the question in the linking table 'editor_question_resources'. Not clear how this happens. Here is an example question with broken resource, https://numbas.mathcentre.ac.uk/question/12546/broken-resource/

**Comment by christianp** [comment]
This happens because when you remove a resource from a question, the resource file is deleted from the server. Copies of the question still have references to that file, which breaks.
I've resolved this in v2.0 by just not deleting the file.
