### ISSUE TITLE
Reorder question groups 

### ISSUE THREAD

**Issue by chrismgraham** [numbas/editor#349]
It should be possible to drag or move up/down question groups in order to rearrange them.

**Comment by christianp** [comment]
To fix this: in [editor/templates/exam/edit.html](https://github.com/numbas/editor/blob/master/editor/templates/exam/edit.html#L69), change the `foreach: question_groups` binding to use a `sortable` binding instead, similar to how [the question lists](https://github.com/numbas/editor/blob/master/editor/templates/exam/edit.html#L95) work. Make sure you set the `group` option to something like `question_groups` so that the two kinds of sortable don't get mixed up.
