### ISSUE TITLE
Getting around question permissions

### ISSUE THREAD

**Issue by WoosterUK** [numbas/editor#390]
[Re-opening https://github.com/numbas/Numbas/issues/505 in correct place.]

If you don't have permission to see a certain question, but you do have permission to see an exam containing it, you can get a copy of the question by downloading the source file of the exam and re-uploading it. This is probably not expected behaviour? Correspondence, with original report, below.

-----Original Message-----
We did discover a way (which may be useful should you need to do something similar): download the source file of the exam and re-upload it to NUMBAS. You magically obtain a copy (with edit access) of all questions in the exam.

Regards,
A

**Comment by christianp** [comment]
One solution is to say that you can only see an exam if you can see all of its questions. I don't think that's good - you could get locked out of an exam by a collaborator inadvertently adding a question that you can't see.

I think I'm going to leave this as "expected behaviour", so it's up to exam authors not to reveal anything they don't want to reveal. The editor doesn't enforce the terms of licences, and I think this is the same category of thing.

**Comment by christianp** [comment]
#397 is a duplicate of this
