### ISSUE TITLE
`ImportError: No module named 'numbasobject'`

### ISSUE THREAD

**Issue by wuffi** [numbas/editor#426]
I tried to follow the instructions for installing the Numbas editor.

Runnning `python first_setup.py` gives me the following error in the end:

    ImportError: No module named 'numbasobject'

My small knowledge on *Python* made me search for this module and I found it in `Numbas/bin`.

How can I make `numbasobject` visible to the numbas editor?

**Comment by christianp** [comment]
Check that `'NUMBAS_PATH'` in `numbas/settings.py` is set to the path of the Numbas compiler.

**Comment by wuffi** [comment]
Thanks a lot for the quick answer.
This was my first guess and I ensured it points to `~/numbas_runtime/bin/`.
Is this correct?

**Comment by wuffi** [comment]
After some trial and error I was able to figure out that the 'NUMBAS_PATH' is just `~/numbas_runtime` (or however one named it).  
Probably obvious to experienced users, but as I beginner, I was a bit confused.

**Comment by wuffi** [comment]
Hi Chris,

I was following <http://numbas.github.io/editor/ubuntu-local.html>.

**Comment by JoshuaCapel** [comment]
Since this issue is being discussed I might append a trivial issue. That page http://numbas.github.io/editor/ubuntu-local.html has title:

> Numbas editor - Mac installation

So when I am looking at the names of the open tabs in my browser it looks like the wrong page.

I was initially planning to push this change onto the repository, but it seems this is something outside of the repository.

**Comment by christianp** [comment]
@JoshuaCapel I've fixed the titles - thanks!

@wuffi - I've added some text about Django to the top of the installation pages, and explicitly listed suggested settings in the "Configuration" step for local use.
